[[client]]
    mac = "84:f3:eb:e3:ef:b1"
    name = "First temperature sensor"
    publicKey = "7kejLYqk34AY90MNyeGIoznGEifdkc9HIN7ahozffhE=" #base64 encoded public key

    [[client.mapping]]
        id = 1
        topic = "home/groundfloor/livingroom/temperature"

    [[client.mapping]]
        id = 2
        topic = "home/sensors/groundfloor/livingroom/voltage"