name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
      
    - name: Get dependencies
      run: |
          cd test && go get -v -t -d ./...
          
  
    - name: Build integration tests
      run: cd test && go build -v .
    - name: Run integration tests
      run: test/main
